version: "3"
services:
  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    restart: unless-stopped
    volumes:
     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./data:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9094:9090
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    ports:
     - "9100:9100"
#    network_mode: host
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
     - "3030:3000"
    depends_on:
      - prom
    volumes:
       - ./grafana_data:/var/lib/grafana

